### ISSUE TITLE
Slip10 Refactor

### ISSUE THREAD

**Issue by nothingismagick** [iotaledger/stronghold.rs#109]
## Transparency
We needed to resolve the complications of SLIP10 (and the fact that hornet doesn't return errors) by compromising our security model and consuming insecure code. This needs to be resolved before the wallet audit, and will require coordination between multiple teams:

- wallet
- crypto
- bee / hornet

**Comment by muXxer** [comment]
Where should hornet return errors?

**Comment by nothingismagick** [comment]
@lucasfernog - I think you are best positioned to address @muXxer 's question

**Comment by lucasfernog** [comment]
We had some trouble with the transaction confirmation state, because stronghold's signing had something wrong and we couldn't detect it. So hornet marks the transaction as conflicting, without telling why. @muXxer

**Comment by rootmos** [comment]
In order to progress we need a set of test vectors that any signer is expected to reproduce:
* the signature data that should be handed to the signing algorithm
* the private key
* it's public key
* the expected signature bytes

@muXxer do you already have this as a test case in the node code?

**Comment by rootmos** [comment]
So, have confirmed that our implementation is producing the same signatures as the implementation from bee-p:
https://github.com/iotaledger/stronghold.rs/blob/f057ef35563a37c421a0e1bf9cded1b018c59f04/client/tests/basic_tests.rs#L320

If the bee-p signatures are accepted (@lucasfernog claims so?), then the issue must either be in the use of strongholds primitives (I see they got changed to accommodate the interfaces from bee-p) or the encoding of the primitives we deliver.

**Comment by nothingismagick** [comment]
Yes, Lucas has confirmed that bee-p signatures are accepted by https://github.com/gohornet/hornet/tree/chrysalis-pt2

**Comment by Wollac** [comment]
@rootmos aren't those test vectors exactly the same as for Ed25519 signing?
Or are you looking for something specific to IOTA transactions?

**Comment by nothingismagick** [comment]
Here is the original test:

https://github.com/wusyong/bee-p/blob/390a7bcfcc524fd8e37c29617c60d2712c3adb67/bee-signing-ext/tests/binary_seed.rs#L67-L78

```rust
#[test]
fn seed_sign_and_verify() {
    let seed = Ed25519Seed::rand();
    let private_key = Ed25519PrivateKey::generate_from_seed(
        &seed,
        &BIP32Path::from_str("m/0H/2147483647H/1H/2147483646H/2H").unwrap(),
    )
    .unwrap();
    let public_key = private_key.generate_public_key();
    let signature = private_key.sign(&[1, 3, 3, 8]);
    public_key.verify(&[1, 3, 3, 8], &signature).unwrap();
}
```

**Comment by Wollac** [comment]
If it helps for your debugging, I've created some artificial test vectors here: https://gist.github.com/Wollac/34c71b04ea7c747d9bc1ae035e19010f

They combine the Slip-10 derivation of a private key with the Ed25519 signing of random message bytes.
As they just combine slip10 and Ed25519 they should, however, not cover anything that the individual tests do not.

**Comment by Wollac** [comment]
One potential caveat with SLIP-10 is that it requires the resulting private key to always be 33 bytes. Since Ed25519 private keys are only 32 bytes the leading byte will always be `0x00`. In the test-vectors from above, I've left this zero out to produce the actual Ed25519-compatible 32-byte private keys.

**Comment by nothingismagick** [comment]
@rootmos and @lucasfernog - waiting for your verification that we can close this issue

**Comment by lucasfernog** [comment]
I'll test it today.

**Comment by nothingismagick** [comment]
Lucas has confirmed that the refactor now works properly.
