### ISSUE TITLE
Secure service for untrusted remote devices

### ISSUE THREAD

**Issue by nothingismagick** [iotaledger/stronghold.rs#11]
## Description

It would be intriguing to make a connection to a node remote service that is running on untrusted hardware and provide it with a seed created in a hardened / trusted service operating within known confines of information-theoretical security.

## Motivation
We can't trust any machine we didn't build ourselves. Cloud providers attempt to give us "faith", but faith is not the same as trust. By creating secrets in an environment we trust and then giving them to the "less-trusted" device, we have an opportunity to enhance operational security. Obviously there are new risks, but it is an intriguing approach, nonetheless.

## Vision

This stronghold would be running on something like a cryptocore (or a smartphone), for example.

**Comment by tensor-programming** [comment]
This is possible with snapshots.  You write the snapshot in a safe environment and send it over to a stronghold in the less safe environment.  If the zone is in place, in theory there shouldn't be a way to access the data from the systems point of view except by using the stronghold interface.
