### ISSUE TITLE
Readable Records

### ISSUE THREAD

**Issue by nothingismagick** [iotaledger/stronghold.rs#110]
## Transparency
In order to provide wallet (and prepare for integration with identity), we took a shortcut and made it possible to read out records. This compromises the general security model of never letting any record in a secure vault being read and disclosed to the caller of the client. There are several approaches that we can take, and the favourable one is to actually append a snapshot with a different type of storage that is read/writable, but requires an entirely different interface as opposed to the general vault/record approach. It will be important to make this datastore available in the same way as all other "secure" stores of data, but internally it will be treated entirely differently.

**Comment by tensor-programming** [comment]
reading records is no longer possible and the store takes the place of the original stronghold for that kind of data.
