### ISSUE TITLE
Bindings

### ISSUE THREAD

**Issue by nothingismagick** [iotaledger/stronghold.rs#15]
## Description

We need to provide bindings to the low-level crates.

## Motivation

Not everyone is comfortable using Rust.

## Requirements

Write a list of what you want this feature to do.

1. C
2. Node.js
3. Python
4. Go

## Open questions (optional)

WASM would be nice, however there is evidence that the memory of a WASM blob is world readable. This is something that needs more investigation.

**Comment by nothingismagick** [comment]
Bindings should ONLY bind to the message receiver and responder. Absolutley no internal access at all. This means that the interface will be necessarily simple.

**Comment by tensor-programming** [comment]
Do you mean mapping to the engine or to the client interface?

**Comment by nothingismagick** [comment]
Only to the client.

**Comment by nothingismagick** [comment]
Here is a resource for making performant go bindings:
https://blog.filippo.io/rustgo/

**Comment by felsweg-iota** [comment]
I'm gonna close this issue in favor of [this discussion](https://github.com/iotaledger/stronghold.rs/discussions/384) to support more automated support on bindings to some major languages.
