### ISSUE TITLE
Document all client features

### ISSUE THREAD

**Issue by lucasfernog** [iotaledger/stronghold.rs#213]
## Description

The crate should include all features when building Rust documentation. This can be done by adding the following code to the Cargo.toml:

```
[package.metadata.docs.rs]
all-features = true
```

It could also specify that certain APIs are behind a feature flag using the unstable [doc_cfg feature](https://doc.rust-lang.org/unstable-book/language-features/doc-cfg.html).

## Motivation

The published documentation under docs.rs does not contain the code behind the `communication` feature, which makes it hard to find and use.

**Comment by tensor-programming** [comment]
Will do.
