### ISSUE TITLE
Stronghold Error: Failed to find Seed Vault.

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/stronghold.rs#244]
## Bug description

Hello,

in the Firefly repository someone reported a Stronghold Error when using Firelfy. (StrongholdError: failed to perform action: Failed to find seed vault. Please generate one) [Firefly Issue #1411]. Are there any hints what can cause this error?

Firefly v1.2

## Hardware specification

What hardware are you using?

- Operating system:
- RAM:
- Cores:
- Device:

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see, including logs, errors, or screenshots.

**Comment by nothingismagick** [comment]
This is a downstream error, in that there is no vault that can be found. It is not a stronghold error per sé.
