### ISSUE TITLE
Store encryption in vault for continuous writing to snapshot on disk

### ISSUE THREAD

**Issue by felsweg-iota** [iotaledger/stronghold.rs#279]
## Description

Writing a snapshot to disk requires a key. Holding this key in memory outside Stronghold is insecure. Provide the means to keep a key inside the vault to enable  writing (to) a snapshot without further providing a key. 

## Motivation

This would enable partial automation of persisting snapshots without keeping the key inside an unsafe memory location. 

## Requirements

Write a list of what you want this feature to do.

1.  extend interface to store a snapshot key, and store the location during the Stronghold session. Make sure that the key itself won't get written into the snapshot itself.

## Open questions (optional)

none. 

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by elenaf9** [comment]
Implemented with #328.
