### ISSUE TITLE
Support reading/ writing of a remote snapshot

### ISSUE THREAD

**Issue by elenaf9** [iotaledger/stronghold.rs#282]
## Description

The Stronghold client currently only supports operations on a remote Stronghold if the remote Stronghold themself has already loaded (read) a snapshot into its system. It should also be possible to request the remote Stronghold to initially read the snapshot, and to write into a new one.

## Motivation

There may be use-cases in which a Stronghold is used exclusively in a remote manner, e.g. if it is on a USB-Armory or a Server. Since in those cases the user does not have local access to the Stronghold to read/write the snapshot, it should be possible to do this from remote.

## Requirements

1. Allow reading a remote snapshot, without exposing the key that is used to access that snapshot
2. Allow writing a remote snapshot, without exposing the key that is used to secure that snapshot
3. The feature should be behind a feature flag and disabled per default.

## Open questions (optional)

**How should the remote obtain the key that is required to read/write the snapshot?**
  Options:
- Send the key as part of the request over the wire to the remote. Encrypt the key in addition to the encryption on the transport layer?
- The remote already has the key (e.g. in its stronghold store, encrypted by a key that is stored in the vault?). When requested to read/write the snapshot, the remote authenticates & validates the requests by the caller's Peer-Id

**Comment by felsweg-iota** [comment]
p2p crate has been dropped.
