### ISSUE TITLE
[Request] Add a procedure to concatenate secrets

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/stronghold.rs#339]
## Description

Add a procedure that concatenates two secrets. Specifically, the functionality requested is this one: https://doc.rust-lang.org/std/primitive.slice.html#method.concat

## Motivation

We need this for the `ECDH-1PU` algorithm that concatenates the secrets generated from two Diffie-Hellman procedures: https://github.com/iotaledger/identity.rs/blob/dd55652ccec75cbe3f095b162e83e8efec6b08ec/libjose/src/jwe/encoder.rs#L701.

See also the relevant section from the RFC: https://datatracker.ietf.org/doc/html/draft-madden-jose-ecdh-1pu-04#section-2.3

## Requirements

Write a list of what you want this feature to do.

- concatenate two secrets

## Open questions (optional)

n/a

## Are you planning to do it yourself in a pull request?

I'm open to it, just let me know.

**Comment by felsweg-iota** [comment]
Hey @PhilippGackstatter, I think this Issue has been resolved by [354](https://github.com/iotaledger/stronghold.rs/pull/354). May you confirm?

**Comment by PhilippGackstatter** [comment]
Unfortunately not. The `ConcatKdf` does something different. This issue really just needs to expose the [`concat`](https://doc.rust-lang.org/std/primitive.slice.html#method.concat) method on slices as a procedure.
