### ISSUE TITLE
Feature to unload snapshot from memory

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/stronghold.rs#394]
## Description

We need a way to ensure that the snapshot is not in memory anymore, we previously used `kill_stronghold` to do that.
We don't really want to completely kill the stronghold instance though, nor reset its state.

## Motivation

We need to be able to lock stronghold when we clear the key.

## Are you planning to do it yourself in a pull request?

No.

**Comment by felsweg-iota** [comment]
@thibault-martinez 
the function `kill_stronghold()` back then reset the `Snapshot` and current `Client` actor, effectively re-setting their in-memory state. Why do you want to just clear the intermediate snapshot state?

**Comment by thibault-martinez** [comment]
Well maybe I don't understand the workflow clearly but we just want to lock stronghold when we clear the key

**Comment by felsweg-iota** [comment]
Ok, so just to be clear ( no pun intended ), the snapshot state shall be blanked out, while the `Client`s state shall be retained? You probably want to load another snapshot?

**Comment by felsweg-iota** [comment]
This issue requires `Stronghold` to provide a function to clear all `Client` and `Snapshot` state. `Stronghold` can be reinitialized by loading the persisted state from the snapshot file.
