### ISSUE TITLE
State corruption when closing the Wallet process (using Node bindings)

### ISSUE THREAD

**Issue by fijter** [iotaledger/stronghold.rs#68]
## Bug description

If you close the application while syncing (either awaiting or in the background) it sometimes corrupts the stronghold state making it unusable.

## Rust version

Which version of Rust are you running?

- Rust version: 1.50.0 nightly

## Version

Which version of the library are you using?

- Version number, commit, or branch: The latest in develop

## Hardware specification

What hardware are you using?

- Operating system: Arch Linux
- RAM: 32 GB
- Cores: 8/16
- Device: Desktop

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Initialize a wallet
2. Call the sync function
3. While the sync function is executing CTRL+C
4. Try to start the wallet again, you might have to repeat 2 and 3 a couple of times because it depends on timing.

## Expected behaviour

State should never be corrupted by termination of the process, should use something like a write-ahead-log.

## Actual behaviour

It breaks

## Errors

```(node:737825) UnhandledPromiseRejectionWarning: Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: unable to decrypt the snapshot
Caused by:
    Snapshot Error: `Snapshot is not valid or encrypted`
    at run (/home/dave/iota/faucet/faucet.js:12:13)
    at Object.<anonymous> (/home/dave/iota/faucet/faucet.js:73:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47```

**Comment by nothingismagick** [comment]
Thanks for the report @fijter - I think I identified one of the underlying causes of the general 'slowness' of the snapshot writing mechanism and that is that we are always recreating the boxing key on every update, which for obvious reasons has to take linear time in order to beat offline attacks. This is only one part of the issue, the other is the fact that we want to avoid corruption at all costs. We are investigating.

**Comment by nothingismagick** [comment]
On a sidenote, it might also be worth your while to catch the `ctrl-c` and use a timeout to allow stronghold to finish its work before exiting. But this doesn't change the validity of the concern.

**Comment by nothingismagick** [comment]
In our call just now, we have identified an approach that should resolve this issue. Write to a temp file, mv to proper filename

**Comment by nothingismagick** [comment]
PR Opened by @rootmos 
https://github.com/iotaledger/stronghold.rs/pull/70

**Comment by nothingismagick** [comment]
This has been resolved. Please reopen if the issue reappears.
