### ISSUE TITLE
[package] field on Cargo.toml

### ISSUE THREAD

**Issue by bernardoaraujor** [iotaledger/stronghold.rs#93]
## Description

`cargo-bitbake` expects a `[package]` field on `Cargo.toml`

## Motivation

Allow cross-compilation via BitBake.

## Requirements

Add `[package]` field to `Cargo.toml`

## Are you planning to do it yourself in a pull request?

I'd be happy to.
However I'm not sure which version to set.

**Comment by nothingismagick** [comment]
We are using the workspace feature of rust, so the `Cargo.toml` does not have a `[package]` entry. Not really sure what you are asking for here. You probably want to consume the `client` crate.

**Comment by bernardoaraujor** [comment]
my bad!
I misinterpreted the output of `cargo bitbake`.

I actually had to add a couple of extra fields to `cli-wallet`'s `Cargo.toml` (which is the project I was trying to BitBake in the first place).

Closing. Sorry for the noise 🙏
